### ISSUE TITLE
Guides gone?

### ISSUE THREAD

**Issue by landlessness** [zettajs/zettajs.github.io#27]
It looks like 'Guides' was removed from the nav.

I refer (myself and other people) to the two guides below fairly often. Have the guides below been ported elsewhere? @WWitman? @mdobson?

http://www.zettajs.org/guides/2014/10/21/How-to-Create-a-Device-Driver.html

http://www.zettajs.org/guides/2014/11/20/How-to-Deploy-Zetta-to-Heroku.html

**Comment by mdobson** [comment]
That content is getting ported over to the wiki on the Zetta project itself. @WWitman is doing his thing to clean it up and make it better.

https://github.com/zettajs/zetta/wiki

**Comment by landlessness** [comment]
thx @mdobson. the wiki is looking great, @WWitman. I pointed the big GitHub button on zettajs.org to it last week. 

so I guess my question is, have those two guides already been ported to the wiki? with a quick search I couldn't find them.

**Comment by kevinswiber** [comment]
It would be great to set up HTTP redirects to the new content.  Does Jekyll
allow that?  In case any previous links or search indexes exist, this would
be a great feature.

**Comment by WWitman** [comment]
@landlessness and @kevinswiber  and @mdobson -- Great points -- I didn't think about redirecting the old topic links as I was moving content over to the wiki. 

The "Deploy to Heroku" topic is here, slightly recast: https://github.com/zettajs/zetta/wiki/Linking-Servers.

I haven't ported over the topic on using the starter driver -- I'll do that tomorrow -- it definitely needs to be in the wiki. 

I'll see if we can do redirects somehow. But if not, I can add a note at the top of the topics in the website that were ported, pointing to the new wikis. That's probably what I'll have to do.

Generally, the new wiki topics in the wiki are not necessarily exact 1-1 conversions from the website topics -- I've done some recasting -- but the ultimate goal is no content left behind.

**Comment by WWitman** [comment]
I moved these guides to the wiki, and added a link in the old guides pointing to the wiki:

http://www.zettajs.org/guides/2014/10/21/How-to-Create-a-Device-Driver.html
http://www.zettajs.org/guides/2014/11/20/How-to-Deploy-Zetta-to-Heroku.html

Putting similar notes in other zettajs.github.io doc topics as I move them over to the wiki.

**Comment by mdobson** [comment]
Awesome! Thanks for the update will.
